L.PDSDA.Web/Areas/Sumber_Daya_Air/Controllers/DASController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using L.PDSDA.Web.Controllers;
using L.PDSDA.DAL.Repositories;
using L.PDSDA.DAL.Entities;
using L.PDSDA.DAL.Repositories.Base;
using L.Core.Utilities;
using L.Core.Utilities.Web;
using L.PDSDA.DAL.Repositories.Implements;
using log4net;
using L.Core.General;

namespace L.PDSDA.Web.Areas.Sumber_Daya_Air.Controllers
{
    public class DASController : BaseController
    {
        private readonly IDefaultRepository<DAS> DefaultRepository;
        private readonly IWSRepository WSRepository;

        ILog log = LogManager.GetLogger(typeof(DASController));

        public DASController()
        {
            this.DefaultRepository = new DefaultRepository<DAS>();
            this.WSRepository = new WSRepository();
            log.InfoFormat("DASController Initialize by {0} at {1}", this.UserLoggedIn, this.UserHostAddress);

        }

        public ActionResult GetDASByWS(string k_ws)
        {
            IQueryable<DAS> qryCollDAS = this.DefaultRepository.Get(x => x.WS.K_WS == k_ws);
            IList<DAS> collDAS = qryCollDAS == null ? new List<DAS>() : qryCollDAS.ToList();

            return Json(new SelectList(collDAS, "K_DAS", "N_DAS"), JsonRequestBehavior.AllowGet);
        }

        void BuildWS()
        {
            IQueryable<WS> collWS = collAssignWS.Count > 0 ? collAssignWS.AsQueryable() : this.WSRepository.GetAll();
            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "", Value = "-1" });
            foreach (var item in collWS)
            {
                collSelectListItem.Add(new SelectListItem { Text = item.K_WS + " - " + item.N_WS, Value = item.K_WS });
            }
            ViewBag.collWS = collSelectListItem;
        }
        //
        // GET: /Sumber_Daya_Air/DAS/

        public ActionResult Index()
        {
            IQueryable<DAS> collDAS = this.DefaultRepository.GetAll();
            return View(collDAS);
        }

        //
        // GET: /Sumber_Daya_Air/DAS/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Sumber_Daya_Air/DAS/Create

        public ActionResult Create()
        {

            if (!IsCreateable)
            {
                return this.Detail("");
            }
            ViewBag.ActionName = "Create";
            BuildWS();

            return PartialView("Save");
        }

        //
        // POST: /Sumber_Daya_Air/DAS/Create

        [HttpPost]
        public ActionResult Create(DAS das)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (das.WS != null && das.WS.K_WS == "-1")
                    {
                        das.WS = null;
                    }
                    log.InfoFormat("DASController Save {2} by {0} at {1}", this.UserLoggedIn, this.UserHostAddress, das.N_DAS);
                    das.CreateBy = this.UserLoggedIn;
                    das.CreateDate = DateTime.Now;
                    das.CreateTerminal = this.UserHostAddress;
                    das.UpdateBy = this.UserLoggedIn;
                    das.UpdateDate = DateTime.Now;
                    das.UpdateTerminal = this.UserHostAddress;
                    this.DefaultRepository.Save(das);
                    return Json(new { success = true, message = Pesan.A1A });

                }
                return Json(new { success = true, message = Pesan.A2A });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.StackTrace });
            }
        }

        //
        // GET: /Sumber_Daya_Air/DAS/Edit/5

        public ActionResult Edit(string id)
        {
            if (!IsUpdateable)
            {
                return this.Detail(id);
            }
            BuildWS();
            DAS DAS = DefaultRepository.Get(x => x.K_DAS == id).FirstOrDefault();
            return PartialView("Save", DAS);
        }
        public ActionResult Detail(string id)
        {
            BuildWS();
            DAS DAS = DefaultRepository.Get(x => x.K_DAS == id).FirstOrDefault();
            return PartialView("Detail", DAS);
        }

        //
        // POST: /Sumber_Daya_Air/DAS/Edit/5

        [HttpPost]
        public ActionResult Edit(string id, DAS das)
        {
            DAS DAS = DefaultRepository.Get(x => x.K_DAS == id).FirstOrDefault();
            if (das.WS != null && das.WS.K_WS == "-1")
            {
                das.WS = null;
            }
            DAS.WS = das.WS;
            Utils.SetTProperty<DAS>(DAS, das);

            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add update logic here
                    log.InfoFormat("DASController Update {2} by {0} at {1}", this.UserLoggedIn, this.UserHostAddress, DAS.N_DAS);
                    DAS.UpdateBy = this.UserLoggedIn;
                    DAS.UpdateDate = DateTime.Now;
                    DAS.UpdateTerminal = this.UserHostAddress;
                    this.DefaultRepository.Update(DAS);
                    //return RedirectToAction("Index");
                    return Json(new { success = true, message = Pesan.A1B });
                }
                return Json(new { success = true, message = Pesan.A2B });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.StackTrace });
            }
        }

        //
        // GET: /Sumber_Daya_Air/DAS/Delete/5

        public ActionResult Delete(string id)
        {
            if (!IsDeleteable)
            {
                return Json(new { success = false, message = Pesan.A2C1 });

            }
            DAS deleteDomain = this.DefaultRepository.Get(x => x.K_DAS == id).FirstOrDefault();
            if (deleteDomain.WS != null && !collAssignWS.Contains(deleteDomain.WS))
            {
                return Json(new { success = false, message = "Tidak berhak hapus data." });
            }
            if (deleteDomain != null)
            {
                log.InfoFormat("DASController Delete {2} by {0} at {1}", this.UserLoggedIn, this.UserHostAddress, deleteDomain.N_DAS);
                SetNullRelation(deleteDomain);
                this.DefaultRepository.Delete(deleteDomain);
                return Json(new { success = true, message = Pesan.A1C });
            }
            return Json(new { success = false, message = Pesan.A2C });
        }


        public ActionResult DeleteAllDAS()
        {
            if (!IsDeleteable)
            {
                return Json(new { success = false, message = Pesan.A2C1 });
            }

            IList<DAS> collDAS = this.DefaultRepository.GetAll().ToList();

            bool IsFail = false;
            foreach (var deleteDomain in collDAS)
            {

                if (deleteDomain.WS != null && !collAssignWS.Contains(deleteDomain.WS))
                {
                    //return Json(new { success = false, message = "Tidak berhak hapus data." });
                    IsFail = true;
                    break;
                }
                if (deleteDomain != null)
                {
                    log.InfoFormat("DASController Delete {2} by {0} at {1}", this.UserLoggedIn, this.UserHostAddress, deleteDomain.N_DAS);
                    SetNullRelation(deleteDomain);
                    this.DefaultRepository.Delete(deleteDomain);
                }
            }
            if (IsFail)
            {
                return Json(new { success = false, message = Pesan.A2C }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = Pesan.A1C }, JsonRequestBehavior.AllowGet);
            }
        }



        private void SetNullRelation(DAS das)
        {
            if (das.AIRTANAHs != null)
                das.AIRTANAHs.ToList().ForEach(x => { x.DAS = null; });
            if (das.BENDUNGANs != null)
                das.BENDUNGANs.ToList().ForEach(x => { x.DAS = null; });
            if (das.BENDUNGs != null)
                das.BENDUNGs.ToList().ForEach(x => { x.DAS = null; });
            if (das.DAERAHRAWANBANJIRs != null)
                das.DAERAHRAWANBANJIRs.ToList().ForEach(x => { x.DA = null; });
            if (das.DAERAHRAWANKEKERINGANs != null)
                das.DAERAHRAWANKEKERINGANs.ToList().ForEach(x => { x.DA = null; });
            if (das.DAERAHRAWANLONGSORs != null)
                das.DAERAHRAWANLONGSORs.ToList().ForEach(x => { x.DA = null; });
            if (das.DANAUs != null)
                das.DANAUs.ToList().ForEach(x => { x.DAS = null; });
            if (das.EMBUNG_POTENSI != null)
                das.EMBUNG_POTENSI.ToList().ForEach(x => { x.DAS = null; });
            if (das.EMBUNGs != null)
                das.EMBUNGs.ToList().ForEach(x => { x.DAS = null; });
            if (das.GUNUNGBERAPIs != null)
                das.GUNUNGBERAPIs.ToList().ForEach(x => { x.DA = null; });
            if (das.IRIGASIs != null)
                das.IRIGASIs.ToList().ForEach(x => { x.DAS = null; });
            if (das.PIDs != null)
                das.PIDs.ToList().ForEach(x => { x.DA = null; });
            if (das.POS_PENGAMAT != null)
                das.POS_PENGAMAT.ToList().ForEach(x => { x.DA = null; });
            if (das.POSKO_BANJIR != null)
                das.POSKO_BANJIR.ToList().ForEach(x => { x.DA = null; });
            if (das.RAWAs != null)
                das.RAWAs.ToList().ForEach(x => { x.DAS = null; });
            if (das.STASIUNDEBITs != null)
                das.STASIUNDEBITs.ToList().ForEach(x => { x.DA = null; });
            if (das.STASIUNHUJANs != null)

L.PDSDA.Web/Areas/Sumber_Daya_Air/Views/DAS/Create.cshtml
@model L.PDSDA.DAL.Entities.DAS
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("Create", "DAS", FormMethod.Post, new { id = "target" }))
{    @Html.ValidationSummary(true)
    <fieldset>
        <legend>DAS</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.K_DAS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_DAS)
            @Html.ValidationMessageFor(model => model.K_DAS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.N_DAS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.N_DAS)
            @Html.ValidationMessageFor(model => model.N_DAS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TANGGUL_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TANGGUL_B)
            @Html.ValidationMessageFor(model => model.TANGGUL_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TANGGUL_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TANGGUL_RR)
            @Html.ValidationMessageFor(model => model.TANGGUL_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TANGGUL_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TANGGUL_RS)
            @Html.ValidationMessageFor(model => model.TANGGUL_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TANGGUL_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TANGGUL_RB)
            @Html.ValidationMessageFor(model => model.TANGGUL_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PARAPET_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PARAPET_B)
            @Html.ValidationMessageFor(model => model.PARAPET_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PARAPET_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PARAPET_RR)
            @Html.ValidationMessageFor(model => model.PARAPET_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PARAPET_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PARAPET_RS)
            @Html.ValidationMessageFor(model => model.PARAPET_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PARAPET_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PARAPET_RB)
            @Html.ValidationMessageFor(model => model.PARAPET_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.REVETMENT_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REVETMENT_B)
            @Html.ValidationMessageFor(model => model.REVETMENT_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.REVETMENT_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REVETMENT_RR)
            @Html.ValidationMessageFor(model => model.REVETMENT_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.REVETMENT_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REVETMENT_RS)
            @Html.ValidationMessageFor(model => model.REVETMENT_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.REVETMENT_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REVETMENT_RB)
            @Html.ValidationMessageFor(model => model.REVETMENT_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.GROUNDSILL_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GROUNDSILL_B)
            @Html.ValidationMessageFor(model => model.GROUNDSILL_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.GROUNDSILL_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GROUNDSILL_RR)
            @Html.ValidationMessageFor(model => model.GROUNDSILL_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.GROUNDSILL_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GROUNDSILL_RS)
            @Html.ValidationMessageFor(model => model.GROUNDSILL_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.GROUNDSILL_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GROUNDSILL_RB)
            @Html.ValidationMessageFor(model => model.GROUNDSILL_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.KRIB_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KRIB_B)
            @Html.ValidationMessageFor(model => model.KRIB_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.KRIB_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KRIB_RR)
            @Html.ValidationMessageFor(model => model.KRIB_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.KRIB_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KRIB_RS)
            @Html.ValidationMessageFor(model => model.KRIB_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.KRIB_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KRIB_RB)
            @Html.ValidationMessageFor(model => model.KRIB_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.SLUICE_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SLUICE_B)
            @Html.ValidationMessageFor(model => model.SLUICE_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.SLUICE_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SLUICE_RR)
            @Html.ValidationMessageFor(model => model.SLUICE_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.SLUICE_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SLUICE_RS)
            @Html.ValidationMessageFor(model => model.SLUICE_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.SLUICE_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SLUICE_RB)
            @Html.ValidationMessageFor(model => model.SLUICE_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.POMPA_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.POMPA_B)
            @Html.ValidationMessageFor(model => model.POMPA_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.POMPA_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.POMPA_RR)
            @Html.ValidationMessageFor(model => model.POMPA_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.POMPA_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.POMPA_RS)
            @Html.ValidationMessageFor(model => model.POMPA_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.POMPA_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.POMPA_RB)
            @Html.ValidationMessageFor(model => model.POMPA_RB)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CHECKDAM_B)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CHECKDAM_B)
            @Html.ValidationMessageFor(model => model.CHECKDAM_B)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CHECKDAM_RR)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CHECKDAM_RR)
            @Html.ValidationMessageFor(model => model.CHECKDAM_RR)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CHECKDAM_RS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CHECKDAM_RS)
            @Html.ValidationMessageFor(model => model.CHECKDAM_RS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CHECKDAM_RB)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CHECKDAM_RB)
            @Html.ValidationMessageFor(model => model.CHECKDAM_RB)
        </div>
        
    </fieldset>
}