L.PDSDA.Web/Areas/Sumber_Daya_Air/Controllers/RawaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using L.PDSDA.DAL.Entities;
using L.PDSDA.DAL.Repositories.Base;
using L.PDSDA.Web.Controllers;
using L.Core.Utilities;
using L.Core.Utilities.Web;

namespace L.PDSDA.Web.Areas.Sumber_Daya_Air.Controllers
{
    public class RawaController : BaseController
    {
        //
        // GET: /Sumber_Daya_Air/Rawa/

        private readonly IDefaultRepository<RAWA> DefaultRepository;
        private readonly IDefaultRepository<WS> WSRepository;
        private readonly IDefaultRepository<DAS> DASRepository;
        private readonly IDefaultRepository<PROPINSI> PROPINSIRepository;
        private readonly IDefaultRepository<KABUPATEN> KABUPATENRepository;

        public RawaController()
        {
            this.DefaultRepository = new DefaultRepository<RAWA>();
            WSRepository = new DefaultRepository<WS>();
            this.DASRepository = new DefaultRepository<DAS>();
            PROPINSIRepository = new DefaultRepository<PROPINSI>();
            this.KABUPATENRepository = new DefaultRepository<KABUPATEN>();
        }

        private void BuildJenis()
        {
            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "Pasang Surut", Value = "P" });
            collSelectListItem.Add(new SelectListItem { Text = "Lebak", Value = "L" });
            ViewBag.collJENIS = collSelectListItem;
        }

        void BuildDAS(string k_ws)
        {
            IQueryable<DAS> collDAS = this.DASRepository.GetAll().Where(x => x.WS.K_WS == k_ws);
            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "", Value = "-1" });
            foreach (var item in collDAS)
            {
                collSelectListItem.Add(new SelectListItem { Text = item.N_DAS, Value = item.K_DAS });
            }
            ViewBag.collDAS = collSelectListItem;
        }

        void BuildWS()
        {
            //IQueryable<WS> collWS = collAssignWS.Count > 0 ? collAssignWS.AsQueryable() : this.WSRepository.GetAll();
            IQueryable<WS> collWS = collAssignWS.Count > 0 ? collAssignWS.AsQueryable() : this.WSRepository.GetAll();
            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "", Value = "-1" });
            foreach (var item in collWS)
            {
                collSelectListItem.Add(new SelectListItem { Text = item.N_WS, Value = item.K_WS });
            }
            ViewBag.collWS = collSelectListItem;
        }

        void BuildPropinsi()
        {
            IQueryable<PROPINSI> collPropinsi = collAssignPropinsi.Count > 0 ? collAssignPropinsi.AsQueryable() : this.PROPINSIRepository.GetAll();

            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "", Value = "-1" });
            foreach (var item in collPropinsi)
            {
                collSelectListItem.Add(new SelectListItem { Text = item.N_PROPINSI, Value = item.K_PROPINSI });
            }
            //new PROPINSI().K_PROPINSI
            ViewBag.collK_PROPINSI = collSelectListItem;
        }

        void BuildKabupaten(string K_PROPINSI)
        {
            IList<SelectListItem> collSelectListItem = new List<SelectListItem>();
            collSelectListItem.Add(new SelectListItem { Text = "", Value = "-1" });
            if (!string.IsNullOrEmpty(K_PROPINSI))
            {
                IQueryable<KABUPATEN> collKABUPATEN = this.KABUPATENRepository.GetAll().Where(x => x.PROPINSI != null && x.PROPINSI.K_PROPINSI == K_PROPINSI);
                foreach (var item in collKABUPATEN)
                {
                    string kodePropinsi = item.PROPINSI == null ? "" : item.PROPINSI.K_PROPINSI;
                    collSelectListItem.Add(new SelectListItem { Text = item.N_KABUPATEN, Value = item.K_KABUPATEN });
                }
            }

            ViewBag.collK_KABUPATEN = collSelectListItem;
        }

        public ActionResult Index()
        {
            IQueryable<RAWA> collRawa = this.DefaultRepository.GetAll();
            return View(collRawa);
        }

        //
        // GET: /Sumber_Daya_Air/Rawa/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Sumber_Daya_Air/WS/Create

        public ActionResult Create()
        {
            if (!IsCreateable)
            {
                return this.Detail("");
            }
            ViewBag.ActionName = "Create";
            BuildDAS(string.Empty);
            BuildWS();
            BuildPropinsi();
            BuildKabupaten(string.Empty);
            BuildJenis();
            return PartialView("Save");
        }

        //
        // POST: /Sumber_Daya_Air/WS/Create

        [HttpPost]
        public ActionResult Create(RAWA rawa)
        {
            try
            {
                // TODO: Add insert logic here

                if (ModelState.IsValid)
                {
                    if (rawa.KABUPATEN != null && rawa.KABUPATEN.K_KABUPATEN == "-1")
                    {
                        rawa.KABUPATEN = null;
                    }

                    if (rawa.PROPINSI != null && rawa.PROPINSI.K_PROPINSI == "-1")
                    {
                        rawa.PROPINSI = null;
                    }
                    if (rawa.WS != null && rawa.WS.K_WS == "-1")
                    {
                        rawa.WS = null;
                    }
                    if (rawa.DAS != null && rawa.DAS.K_DAS == "-1")
                    {
                        rawa.DAS = null;
                    }
                    rawa.CreateBy = this.UserLoggedIn;
                    rawa.CreateDate = DateTime.Now;
                    rawa.CreateTerminal = this.UserHostAddress;
                    rawa.UpdateBy = this.UserLoggedIn;
                    rawa.UpdateDate = DateTime.Now;
                    rawa.UpdateTerminal = this.UserHostAddress;
                    this.DefaultRepository.SaveOrUpdate(rawa);
                }
                return Json(new { success = true, message = "Data telah disimpan." });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.StackTrace });
            }
        }

        //
        // GET: /Sumber_Daya_Air/WS/Edit/5

        public ActionResult Edit(string id)
        {
            if (!IsUpdateable)
            {
                return this.Detail(id);
            }

            RAWA RAWA = DefaultRepository.Get(x => x.K_RAWA == id).FirstOrDefault();
            BuildWS();
            BuildDAS(RAWA.WS == null ? string.Empty : RAWA.WS.K_WS);
            BuildPropinsi();
            BuildJenis();
            BuildKabupaten(RAWA.PROPINSI == null ? "" : RAWA.PROPINSI.K_PROPINSI);
            if (RAWA.WS != null && !collAssignWS.Contains(RAWA.WS))
            {
                IList<SelectListItem> addWStoSelectedListItem = new List<SelectListItem>(); //ViewBag.collWS = addWStoSelectedListItem;
                addWStoSelectedListItem.Add(new SelectListItem() { Text = RAWA.WS.N_WS, Value = RAWA.WS.K_WS, Selected = true });
                ViewBag.collWS = addWStoSelectedListItem;
                ViewBag.ActionName = "Detail";
                return PartialView("Detail", RAWA);
                //return Detail(id);
            }
            ViewBag.ActionName = "Edit";
            return PartialView("Save", RAWA);
        }
        public ActionResult Detail(string id)
        {
            ViewBag.ActionName = "Detail";

            RAWA RAWA = DefaultRepository.Get(x => x.K_RAWA == id).FirstOrDefault();
            BuildWS();
            BuildDAS(RAWA != null ? RAWA.WS == null ? string.Empty : RAWA.WS.K_WS : "");
            BuildPropinsi();
            BuildJenis();
            BuildKabupaten(RAWA != null ? RAWA.PROPINSI == null ? "" : RAWA.PROPINSI.K_PROPINSI : "");
            return PartialView("Detail", RAWA);
        }

        //
        // POST: /Sumber_Daya_Air/WS/Edit/5

        [HttpPost]
        public ActionResult Edit(string id, RAWA rawa)
        {
            string kodePropinsi = rawa.PROPINSI.K_PROPINSI;
            if (rawa.PROPINSI != null && rawa.PROPINSI.K_PROPINSI == "-1")
            {
                rawa.PROPINSI = null;
            }
            if (rawa.KABUPATEN != null && rawa.KABUPATEN.K_KABUPATEN == "-1")
            {
                rawa.KABUPATEN = null;
            }
            if (rawa.WS != null && rawa.WS.K_WS == "-1")
            {
                rawa.WS = null;
            }
            if (rawa.DAS != null && rawa.DAS.K_DAS == "-1")
            {
                rawa.DAS = null;
            }

            if (kodePropinsi != "-1" && rawa.KABUPATEN == null)
            {
                return Json(new { success = false, message = "Pilih Kabupaten terlebih dahulu." });
            }

            RAWA RAWA = DefaultRepository.Get(x => x.K_RAWA == id).FirstOrDefault();
            RAWA.DAS = rawa.DAS;
            RAWA.WS = rawa.WS;
            RAWA.PROPINSI = rawa.PROPINSI;
            RAWA.KABUPATEN = rawa.KABUPATEN;
            RAWA.LatLong = rawa.LatLong;
            Utils.SetTProperty<RAWA>(RAWA, rawa);

            try
            {


                if (ModelState.IsValid)
                {
                    RAWA.UpdateBy = this.UserLoggedIn;
                    RAWA.UpdateDate = DateTime.Now;
                    RAWA.UpdateTerminal = this.UserHostAddress;
                    this.DefaultRepository.SaveOrUpdate(RAWA);
                    //return RedirectToAction("Index");
                    return Json(new { success = true, message = "Data telah diubah" });

L.PDSDA.Web/Areas/Sumber_Daya_Air/Views/Rawa/Create.cshtml
@model L.PDSDA.DAL.Entities.RAWA

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "Rawa", FormMethod.Post, new { id = "target" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>RAWA</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_RAWA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_RAWA)
            @Html.ValidationMessageFor(model => model.K_RAWA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.N_RAWA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.N_RAWA)
            @Html.ValidationMessageFor(model => model.N_RAWA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_PROPINSI)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_PROPINSI)
            @Html.ValidationMessageFor(model => model.K_PROPINSI)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_KABUPATEN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_KABUPATEN)
            @Html.ValidationMessageFor(model => model.K_KABUPATEN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.KECAMATAN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KECAMATAN)
            @Html.ValidationMessageFor(model => model.KECAMATAN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DESA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DESA)
            @Html.ValidationMessageFor(model => model.DESA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.JENIS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.JENIS)
            @Html.ValidationMessageFor(model => model.JENIS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_WS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_WS)
            @Html.ValidationMessageFor(model => model.K_WS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_DAS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_DAS)
            @Html.ValidationMessageFor(model => model.K_DAS)
        </div>

      
    </fieldset>
}

L.PDSDA.Web/Areas/Sumber_Daya_Air/Views/Rawa/Edit.cshtml
@model L.PDSDA.DAL.Entities.RAWA

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "Rawa", FormMethod.Post, new { id = "target" }))
{   @Html.ValidationSummary(true)
    <fieldset>
        <legend>RAWA</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_RAWA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_RAWA)
            @Html.ValidationMessageFor(model => model.K_RAWA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.N_RAWA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.N_RAWA)
            @Html.ValidationMessageFor(model => model.N_RAWA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_PROPINSI)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_PROPINSI)
            @Html.ValidationMessageFor(model => model.K_PROPINSI)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_KABUPATEN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_KABUPATEN)
            @Html.ValidationMessageFor(model => model.K_KABUPATEN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.KECAMATAN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KECAMATAN)
            @Html.ValidationMessageFor(model => model.KECAMATAN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DESA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DESA)
            @Html.ValidationMessageFor(model => model.DESA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.JENIS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.JENIS)
            @Html.ValidationMessageFor(model => model.JENIS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_WS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_WS)
            @Html.ValidationMessageFor(model => model.K_WS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.K_DAS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_DAS)
            @Html.ValidationMessageFor(model => model.K_DAS)
        </div>

        
    </fieldset>
}

L.PDSDA.Web/Areas/Sumber_Daya_Air/Views/Rawa/Save.cshtml
@model L.PDSDA.DAL.Entities.RAWA
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/js/myjs.js")" type="text/javascript"></script>
<script>
    function fnLoadRawaDyn(oThis) {

        var IsViewable = "@ViewBag.IsViewable";
        var IsCreateable = "@ViewBag.IsCreateable";
        var IsUpdateable = "@ViewBag.IsUpdateable";
        var IsDeleteable = "@ViewBag.IsDeleteable";

        var id = $("#K_RAWA").val();  //$("input[type=hidden]").val()
        oThis.href = '@Url.Content("~/Sumber_Daya_Air/RawaDyn/Index")' + "?id=" + id.replace(/ /g, '%20%') + "&IsViewable=" + IsViewable + "&IsCreateable=" + IsCreateable + "&IsUpdateable=" + IsUpdateable + "&IsDeleteable=" + IsDeleteable;
        oThis.title = "Rawa Dyn"

        //        var $loading = $('<img src="images/ajaxLoading.gif" height="20" width = "20"  alt="loading" class="ui-loading-icon">');
        var $url = oThis.href;
        var $title = oThis.title;
        var $dialog = $('<div id="divRawaDynTable"></div>');

        initialized("@Request.ApplicationPath");
        fnLoading();
        $dialog
		.load($url, function (response, status, xhr) {
		    if (status == "success") {
		        dialogLoading.dialog("close"); $dialog.dialog('open');
		    }
		})
		    .dialog({ closeOnEscape: false,
		        position: "top",
		        autoOpen: false
			    , title: $title
			    , width: 1000
	        	    , modal: true
			    , minHeight: 100
	        	    , show: 'fade'
		        //	        	, hide: 'fade'
		    });

        $dialog.dialog("option", "buttons", {
            "Tutup": function () {
                $($dialog).dialog("close");
                $($dialog).empty();
                //		            parent.$("table").fnDraw();
                //                window.location.reload(true);
            }
        });

        //        $dialog.dialog('open');
    }

    $(function () {
        var oKABUPATEN_PROPINSI_K_PROPINSI = $('#KABUPATEN_PROPINSI_K_PROPINSI');
        var oKABUPATEN_K_KABUPATEN = $('#KABUPATEN_K_KABUPATEN');

        oKABUPATEN_PROPINSI_K_PROPINSI.change(function () {
            var value = oKABUPATEN_PROPINSI_K_PROPINSI.val();
            $.getJSON('@Url.Content("~/Master/Kabupaten/GetKabupatenByPropinsi/?")' + "propinsiid=" + value.replace(/ /g, '%20%'), function (data) {
                var items = '<option value="-1">Pilih Kabupaten</option>';
                $.each(data, function (i, kabupaten) {
                    items += "<option value='" + kabupaten.Value + "'>" + kabupaten.Text + "</option>";
                });
                oKABUPATEN_K_KABUPATEN.html(items);
            });
        });

        var DAS_K_DAS = $('#DAS_K_DAS');
        var WS_K_WS = $('#WS_K_WS');

        WS_K_WS.change(function () {
            var value = WS_K_WS.val();
            $.getJSON('@Url.Content("~/Sumber_Daya_Air/DAS/GetDASByWS/")' + "?k_ws=" + value.replace(/ /g, '%20%'), function (data) {
                var items = '<option value="-1">Pilih DAS</option>';
                $.each(data, function (i, kabupaten) {
                    items += "<option value='" + kabupaten.Value + "'>" + kabupaten.Text + "</option>";
                });
                DAS_K_DAS.html(items);
            });
        });

    });

    
</script>
@using (Html.BeginForm(@ViewBag.ActionName as string, "Rawa", FormMethod.Post, new { id = "target" }))
{
    
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>RAWA</legend>
        <div class="editor-label">
            Kode Rawa
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.K_RAWA)
            @Html.ValidationMessageFor(model => model.K_RAWA)
        </div>
        <div class="editor-label">
            Nama Rawa
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.N_RAWA)
            @Html.ValidationMessageFor(model => model.N_RAWA)
        </div>
        <div class="editor-label">
            Propinsi
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.KABUPATEN.PROPINSI.K_PROPINSI, ViewBag.collK_PROPINSI as IList<SelectListItem>)
            @Html.ValidationMessageFor(x => x.KABUPATEN.PROPINSI.K_PROPINSI)
        </div>
        <div class="editor-label">
            Kabupaten
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.KABUPATEN.K_KABUPATEN, ViewBag.collK_KABUPATEN as IList<SelectListItem>)
            @Html.ValidationMessageFor(x => x.KABUPATEN.K_KABUPATEN)
        </div>
        <div class="editor-label">
            Nama WS
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.WS.K_WS, ViewBag.collWS as IList<SelectListItem>)
            @Html.ValidationMessageFor(x => x.WS.K_WS)
        </div>
        <div class="editor-label">
            Nama DAS
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.DAS.K_DAS, ViewBag.collDAS as IList<SelectListItem>)
            @Html.ValidationMessageFor(x => x.DAS.K_DAS)
        </div>
        <div class="editor-label">
            Kecamatan
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KECAMATAN)
            @Html.ValidationMessageFor(model => model.KECAMATAN)
        </div>
        <div class="editor-label">
            Desa
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DESA)
            @Html.ValidationMessageFor(model => model.DESA)
        </div>
        <div class="editor-label">
            Jenis
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(x => x.JENIS, ViewBag.collJENIS as IList<SelectListItem>)
            @Html.ValidationMessageFor(x => x.JENIS)
        </div>
        <div class="editor-label">
            Latitude
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LatLong.Latitude)
            @Html.ValidationMessageFor(model => model.LatLong.Latitude)
        </div>
        <div class="editor-label">
            Longitude
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LatLong.Longitude)
            @Html.ValidationMessageFor(model => model.LatLong.Longitude)
        </div>
        <div class="editor-field">
            <script type="text/javascript">
                function loadMap() {
                    var oThis = {};
                    oThis.href = '@Url.Content("~/Peta/GenericMap/IndexWithClick/")';
                    oThis.title = "Peta";
                    loadDialogMap(oThis, "divFormGenericPeta", $(window).width() - 150, $(window).height() - 200)
                }
            </script>
            <a href="javascript:loadMap()" class="modalDlg, clsButtonAdd">Map</a>
        </div>
    </fieldset>
}
<a href="javascript:fnLoadRawaDyn(this)" class="modalDlg, clsButtonAdd">Infrastruktur</a>