L.PDSDA.Web/Areas/Hidrologi/Controllers/PosDugaAirDynController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Globalization;
using L.Core.General;
using L.Core.Utilities.Web;
using L.PDSDA.DAL.Entities;
using L.Core.Utilities;
using L.PDSDA.Web.DTOs;
using L.PDSDA.Web.Controllers;
using L.PDSDA.DAL.Repositories.Base;

namespace L.PDSDA.Web.Areas.Hidrologi.Controllers
{
    public class PosDugaAirDynController : BaseController
    {
        IDefaultRepository<STASIUNDEBIT> StasiunDebitRepository;

        IDefaultRepository<STASIUNDEBIT_DYN> DefaultRepository;

        public PosDugaAirDynController()
        {
            DefaultRepository = new DefaultRepository<STASIUNDEBIT_DYN>();
            StasiunDebitRepository = new DefaultRepository<STASIUNDEBIT>();
        }
        //
        // GET: /DaerahIrigasi/IrigasiDyn/

        public ActionResult Index()
        {
            string K_STASIUN = Utils.GetQueryString("id");
            STASIUNDEBIT STASIUNDEBIT = this.StasiunDebitRepository.Get(x => x.K_STASIUN == K_STASIUN).FirstOrDefault();
            if (STASIUNDEBIT != null)
            {
                if (STASIUNDEBIT.W != null && !collAssignWS.Contains(STASIUNDEBIT.W))
                {
                    ViewBag.IsViewable = false;
                    ViewBag.IsCreateable = false;
                    ViewBag.IsUpdateable = false;
                    ViewBag.IsDeleteable = false;
                    ViewBag.Method = Utils.GetPostRequest("method");
                    return PartialView("Index", K_STASIUN);
                }
            }
            return PartialView("Index", K_STASIUN);
        }

        //
        // GET: /Bencana/STASIUNDEBIT_DYN/Create

        void GetCodeAndYear()
        {
            string K_STASIUN = Utils.GetQueryString("K_STASIUN");
            ViewBag.K_STASIUN = K_STASIUN;
            IQueryable<STASIUNDEBIT_DYN> qrySTASIUNDEBIT_DYN = this.DefaultRepository.Get(x => x.STASIUNDEBIT != null && x.STASIUNDEBIT.K_STASIUN == K_STASIUN);
            IList<STASIUNDEBIT_DYN> collSTASIUNDEBIT_DYN = null;
            string sTahun = "";
            if (qrySTASIUNDEBIT_DYN != null)
            {
                collSTASIUNDEBIT_DYN = qrySTASIUNDEBIT_DYN.ToList();
            }
            if (collSTASIUNDEBIT_DYN != null && collSTASIUNDEBIT_DYN.Count > 0)
            {
                for (int i = 0; i < collSTASIUNDEBIT_DYN.Count; i++)
                {
                    if (string.IsNullOrEmpty(sTahun))
                    {
                        sTahun = collSTASIUNDEBIT_DYN[i].TAHUN.ToString();
                    }
                    else
                    {
                        sTahun = sTahun + "," + collSTASIUNDEBIT_DYN[i].TAHUN.ToString();
                    }
                }
            }
            ViewBag.collTahun = sTahun;
        }

        public ActionResult Create()
        {
            if (!IsCreateable)
            {
                //return this.GenericViewDefault();
                return this.Detail("");
            }
            ViewBag.ActionName = "Create";
            GetCodeAndYear();
            this.Session.Remove("DebitAirEvents");
            this.Session.Remove("TinggiMukaAirEvents");
            return PartialView("Save");
        }

        //
        // POST: /Bencana/STASIUNDEBIT_DYN/Create

        [HttpPost]
        public ActionResult Create(STASIUNDEBIT_DYN domain)
        {
            string K_STASIUN = Utils.GetQueryString("K_STASIUN");
            STASIUNDEBIT STASIUNDEBIT = this.StasiunDebitRepository.Get(x => x.K_STASIUN == K_STASIUN).FirstOrDefault();
            domain.STASIUNDEBIT = STASIUNDEBIT;

            if (Session["DEBIT"] != null)
            {
                domain.DEBIT = Session["DEBIT"] as byte[];
            }
            if (Session["TMA"] != null)
            {
                domain.TMA = Session["TMA"] as byte[];
            }

            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    this.DefaultRepository.Save(domain);
                    return Json(new { success = true, message = "Data telah disimpan." });

                }
                return Json(new { success = true, message = "Invalid Model State" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.StackTrace });
            }
        }

        //
        // GET: /Bencana/STASIUNDEBIT_DYN/Edit/5

        public ActionResult Edit(string id)
        {
            string[] arr = id.Split(',');

            if (!IsUpdateable)
            {
                //return this.GenericViewDefault();
                return this.Detail(id);
            }
            ViewBag.ActionName = "Edit";
            //GetCodeAndYear();
            ViewBag.K_STASIUN = arr[0];
            ViewBag.TAHUN = arr[1];
            STASIUNDEBIT_DYN domain = DefaultRepository.Get(x => x.TAHUN == Convert.ToInt32(arr[1]) && (x.STASIUNDEBIT != null && x.STASIUNDEBIT.K_STASIUN == arr[0])).FirstOrDefault();

            IList<Utils.NameValue> DebitAirEvents = new List<Utils.NameValue>();
            if (domain.DEBIT != null)
            {
                if (Session["DEBIT"] != null)
                {
                    this.Session.Remove("DEBIT");
                }


                this.Session.Add("DEBIT", domain.DEBIT);

                using (Stream stream = new MemoryStream(domain.DEBIT))
                {
                    StreamReader reader = new StreamReader(stream);
                    string lines = string.Empty;
                    while ((lines = reader.ReadLine()) != null)
                    {
                        //string text = reader.ReadLine();
                        string[] texts = lines.Split(',');
                        Utils.NameValue NameValue = new Utils.NameValue();
                        NameValue.Name = texts[0];
                        NameValue.Value = texts[1];
                        DebitAirEvents.Add(NameValue);
                        lines = string.Empty;
                    }
                }
            }

            IList<Utils.NameValue> TMAEvents = new List<Utils.NameValue>();

            if (domain.TMA != null)
            {
                if (Session["TMA"] != null)
                {
                    this.Session.Remove("TMA");
                }


                this.Session.Add("TMA", domain.TMA);

                using (Stream stream = new MemoryStream(domain.TMA))
                {
                    StreamReader reader = new StreamReader(stream);
                    string lines = string.Empty;
                    while ((lines = reader.ReadLine()) != null)
                    {
                        //string text = reader.ReadLine();
                        string[] texts = lines.Split(',');
                        Utils.NameValue NameValue = new Utils.NameValue();
                        NameValue.Name = texts[0];
                        NameValue.Value = texts[1];
                        TMAEvents.Add(NameValue);
                        lines = string.Empty;
                    }
                }
            }



            STASIUNDEBIT_DYNDTO STASIUNDEBIT_DYNDTO = new STASIUNDEBIT_DYNDTO();
            STASIUNDEBIT_DYNDTO.STASIUNDEBIT_DYN = domain;
            STASIUNDEBIT_DYNDTO.DebitAirEvents = new List<jQueryFullCalendarEventModel>();
            STASIUNDEBIT_DYNDTO.TinggiMukaAirEvents = new List<jQueryFullCalendarEventModel>();
            DebitAirEvents.ToList().ForEach(delegate(Utils.NameValue nv)
            {
                if (Utils.TryParseToDouble(nv.Value) > 0)
                {

                    jQueryFullCalendarEventModel jQueryFullCalendarEventModel = new jQueryFullCalendarEventModel();
                    //jQueryFullCalendarEventModel.id = Convert.ToDateTime(nv.Name, CultureInfo.GetCultureInfo("id-ID"));
                    //jQueryFullCalendarEventModel.start = Convert.ToDateTime(nv.Name, CultureInfo.GetCultureInfo("id-ID"));

                    jQueryFullCalendarEventModel.id = nv.Name;
                    jQueryFullCalendarEventModel.start = DateTime.ParseExact(nv.Name, "d-MM-yyyy", new CultureInfo("en-US")).ToString("yyyy-MM-dd");//, new CultureInfo(""), DateTimeStyles.NoCurrentDateDefault).ToString("yyyy-MM-dd");// Convert.ToDateTime(nv.Name).ToString("yyyy-MM-dd");
                    jQueryFullCalendarEventModel.end = DateTime.ParseExact(nv.Name, "d-MM-yyyy", new CultureInfo("en-US")).ToString("yyyy-MM-dd");// Convert.ToDateTime(nv.Name).ToString("yyyy-MM-dd");
                    jQueryFullCalendarEventModel.title = nv.Value;
                    jQueryFullCalendarEventModel.allDay = true;
                    STASIUNDEBIT_DYNDTO.DebitAirEvents.Add(jQueryFullCalendarEventModel);
                }

            });

            if (this.Session["DebitAirEvents"] != null)
            {
                this.Session.Remove("DebitAirEvents");
            }
            this.Session.Add("DebitAirEvents", STASIUNDEBIT_DYNDTO.DebitAirEvents);

            TMAEvents.ToList().ForEach(delegate(Utils.NameValue nv)
            {
                if (Utils.TryParseToDouble(nv.Value) > 0)
                {
                    jQueryFullCalendarEventModel jQueryFullCalendarEventModel = new jQueryFullCalendarEventModel();
                    //jQueryFullCalendarEventModel.id = Convert.ToDateTime(nv.Name, CultureInfo.GetCultureInfo("id-ID"));
                    //jQueryFullCalendarEventModel.start = Convert.ToDateTime(nv.Name, CultureInfo.GetCultureInfo("id-ID"));

                    jQueryFullCalendarEventModel.id = nv.Name;

L.PDSDA.Web/Areas/Hidrologi/Views/PosDugaAirDyn/DebitAirSaveV2.cshtml
@using L.Core.Utilities
@{
    TextWriter tw = new StringWriter();
    Json.Write(this.Session["DebitAirEvents"] == null ? null : this.Session["DebitAirEvents"], tw);
    var Events = HttpUtility.HtmlDecode(tw.ToString());
    ViewBag.Title = "Data Debit Air Harian";
    var Action = ViewBag.ActionName;
    var K_STASIUN = ViewBag.K_STASIUN;
    var collTahun = ViewBag.collTahun;
    var TAHUN = L.Core.Utilities.Utils.GetQueryString("tahun");
    var method = Utils.GetQueryString("method");
}
<div id='calendarda' style="visibility: hidden">
</div>
<br />
@if (method != "Detail")
{
    <a id="btnTestBlobda" href="#" class="clsButtonAdd">Selesai Ubah Data</a>
}
<div id="divNilaiHarianda" style="visibility: hidden; width: 250px">
    <input type="text" id="txtNilaiHarianda" />
    <input type="button" value="Ubah Data" id="btnSimpanDanKeluarda" />
    <input type="hidden" id="dateInYearda" />
</div>
<link href='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.css")' rel='stylesheet' />
<link href='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.print.css")' rel='stylesheet' media='print' />
<script src='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.min.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Content/plugin/underscore-min.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Content/js/myjs.js")' type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
*@
<script type="text/javascript">
    var calendarda = $('#calendarda');
    var btnTestBlobda = $("#btnTestBlobda");
    var yearda = "@TAHUN";
    var dateInYearda = $("#dateInYearda");
    var btnSimpanDanKeluarda = $("#btnSimpanDanKeluarda");
    var storedEvents = _.unescape("@Events");

    $(function () {
        initialized("@Request.ApplicationPath");
        BuildCalendar(yearda);
        calendarda.removeAttr("style");
    });

    //btnTestBlobda
    btnTestBlobda.click(function () {
        fnLoading();
        var events = calendarda.fullCalendar('clientEvents');
        var sortEvents = _.sortBy(events, function (data) { return data.start; })
        var obj = new Array();
        for (var i = 0; i < sortEvents.length; i++) {
            var event = sortEvents[i];
            var id;
            try {
                id = $.fullCalendar.formatDate(event.id, "dd-MM-yyyy");
            } catch (e) {
                id = event.id;
            }
            var title = event.title;
            obj.push({ id: id, title: title });
        }
        $.ajax({
            url: '@Url.Action("SetToCacheDebitAir", "PosDugaAirDyn")' + "?TAHUN=" + yearda + "&K_STASIUN=@K_STASIUN",
            data: JSON.stringify(obj),
            type: 'POST',
            contentType: 'application/json; charset=utf-8'
            , success: function (response) {
                if (response.message.valueOf() == 'at NHibernate.Id.Assigned.Generate') {
                    alert('Kode / Id Tidak Boleh Kosong');
                    return false;
                }
                else {
                    alert(response.message);
                }
                dialogLoading.dialog("close");
                return false;
            },
            error: function (xhr) {
                alert(xhr.message);

                if (xhr.status == 400)
                    dlg.html(xhr.responseText, xhr.status);     /* display validation errors in this dialog */
                else {
                    alert(xhr);
                }
                dialogLoading.dialog("close");
            }
        });
    })

    function BuildCalendar(yearda) {
        var date = $.datepicker.parseDate("dd-mm-yy", "01-01-" + yearda);
        var d = date.getDate();
        var m = date.getMonth();
        var y = yearda;
        var json = $.parseJSON(storedEvents);
        calendarda = $('#calendarda').fullCalendar({
            year: y,
            month: 0,
            date: 1,
            defaultView: 'month',
            header: {
                left: 'prev,next',
                center: 'title',
                right: 'month'
            },
            disableDragging: true,
            selectable: true,
            selectHelper: true,

            viewDisplay: function (view) {
                var now = $.datepicker.parseDate("dd-mm-yy", "01-01-" + yearda);
                var end = $.datepicker.parseDate("dd-mm-yy", "01-01-" + yearda);
                end.setMonth(now.getMonth() + 11); //Adjust as needed
                var cal_date_string = view.start.getMonth() + '/' + view.start.getFullYear();
                var cur_date_string = now.getMonth() + '/' + now.getFullYear();
                var end_date_string = end.getMonth() + '/' + end.getFullYear();
                if (cal_date_string == cur_date_string) { jQuery('.fc-button-prev').addClass("fc-state-disabled"); }
                else { jQuery('.fc-button-prev').removeClass("fc-state-disabled"); }
                if (end_date_string == cal_date_string) { jQuery('.fc-button-next').addClass("fc-state-disabled"); }
                else { jQuery('.fc-button-next').removeClass("fc-state-disabled"); }
            },
            select: function (start, end, allDay) {
                var id = $.fullCalendar.formatDate(start, "d-MM-yyyy");
                var event = calendarda.fullCalendar('clientEvents', id);
                dateInYearda.val(id);
                var title = "";
                try {
                    title = event[0].title;
                } catch (e) {
                }
                if ("@method" != "Detail") {
                    $("#txtNilaiHarianda").val(title);
                    $("#divNilaiHarianda").removeAttr("style");
                    $("#divNilaiHarianda").dialog({ modal: true });
                }
            },
            editable: true,
            events: json,
            close: function () { }
        })
    }

    //btnSimpanDanKeluarda
    btnSimpanDanKeluarda.click(function () {
        var date = $.datepicker.parseDate("dd-mm-yy", dateInYearda.val());
        if (date.getFullYear() != yearda) {
            alert('tahun tidak berada pada tahun yang sama');
            return;
        }
        date = $.fullCalendar.formatDate(date, "d-MM-yyyy");
        var event = calendarda.fullCalendar('clientEvents', date);
        if (date && $("#txtNilaiHarianda").val()) {
            if (!$.isNumeric($("#txtNilaiHarianda").val())) {
                alert('harap masukkan angka');
                return;
            }
            if (event) {
                $('#calendarda').fullCalendar('removeEvents', date);
            }
            var dateStart = $.datepicker.parseDate("dd-mm-yy", dateInYearda.val());
            $("#calendarda").fullCalendar('renderEvent',
                {
                    id: date, // $.fullCalendar.formatDate(start, "dd-MM-yyyy"),
                    title: $("#txtNilaiHarianda").val(),
                    start: dateStart
                },
                true // make the event "stick"
            );
        }
        $("#divNilaiHarianda").dialog('close');
        $("#divNilaiHarianda").dialog("destroy");
        $("#divNilaiHarianda").css("visibility", "hidden");
    });
</script>

L.PDSDA.Web/Areas/Hidrologi/Views/PosDugaAirDyn/TMASaveV2.cshtml
@*@model L.PDSDA.Web.DTOs.STASIUNDEBIT_DYNDTO*@
@using L.Core.Utilities
@{
    //var STASIUNDEBIT_DYN = Model == null ? null : Model.STASIUNDEBIT_DYN;
    //TextWriter tw = new StringWriter();
    //Json.Write(Model == null ? null : Model.DebitAirEvents, tw);
    TextWriter tw = new StringWriter();
    Json.Write(this.Session["TinggiMukaAirEvents"] == null ? null : this.Session["TinggiMukaAirEvents"], tw);
    var Events = HttpUtility.HtmlDecode(tw.ToString());
    ViewBag.Title = "Tinggi Muka Air Harian";
    var Action = ViewBag.ActionName;
    var K_STASIUN = ViewBag.K_STASIUN;
    var collTahun = ViewBag.collTahun;
    var TAHUN = L.Core.Utilities.Utils.GetQueryString("tahun");
    var method = Utils.GetQueryString("method");
}

@*<form id="myform">*@
<div id='calendar' style="visibility: hidden">
</div>
<br />
@if (method != "Detail")
{
    <a id="btnTestBlob" href="#" class="clsButtonAdd">Selesai Ubah Data</a>
}
<div id="divNilaiHarian" style="visibility: hidden; width: 250px">
    <input type="text" id="txtNilaiHarian" />
    <input type="button" value="Ubah Data" id="btnSimpanDanKeluar" />
    <input type="hidden" id="dateInYear" />
</div>
@*</form>*@

<link href='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.css")' rel='stylesheet' />
<link href='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.print.css")' rel='stylesheet' media='print' />
<script src='@Url.Content("~/Content/plugin/fullcalendar/fullcalendar.min.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Content/plugin/underscore-min.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Content/js/myjs.js")' type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    //    $("#myform").validate({
    //        rules: {
    //            txtNilaiHarian: {
    //                required: true,
    //                number: true
    //            }
    //        }
    //    });

    var calendar = $('#calendar');
    var btnTestBlob = $("#btnTestBlob");
    var year = "@TAHUN";
    var dateInYear = $("#dateInYear");
    var btnSimpanDanKeluar = $("#btnSimpanDanKeluar");
    var storedEvents = _.unescape("@Events");

    $(function () {
        initialized("@Request.ApplicationPath");
        BuildCalendar(year);
        calendar.removeAttr("style");
    });



    //btnTestBlob
    btnTestBlob.click(function () {
        fnLoading();
        var events = calendar.fullCalendar('clientEvents');
        var sortEvents = _.sortBy(events, function (data) { return data.start; })
        //        console.log(sortEvents);
        var obj = new Array();

        for (var i = 0; i < sortEvents.length; i++) {
            var event = sortEvents[i];
            var id;
            try {
                id = $.fullCalendar.formatDate(event.id, "dd-MM-yyyy");
            } catch (e) {
                id = event.id;
            }
            var title = event.title;
            obj.push({ id: id, title: title });
        }
        //        console.log(JSON.stringify(obj));
        $.ajax({
            url: '@Url.Action("SetToCacheTMA", "PosDugaAirDyn")' + "?TAHUN=" + year + "&K_STASIUN=@K_STASIUN",
            data: JSON.stringify(obj),
            type: 'POST',
            contentType: 'application/json; charset=utf-8'
            , success: function (response) {
                if (response.message.valueOf() == 'at NHibernate.Id.Assigned.Generate') {
                    alert('Kode / Id Tidak Boleh Kosong');
                    return false;
                }
                else {
                    alert(response.message);
                }
                //                if (response.success) {
                //                    dlg.dialog('close');
                //                    dlg.empty();
                //                }
                dialogLoading.dialog("close");
                return false;
            },
            error: function (xhr) {
                alert(xhr.message);

                if (xhr.status == 400)
                    dlg.html(xhr.responseText, xhr.status);     /* display validation errors in this dialog */
                else {
                    alert(xhr);
                }
                dialogLoading.dialog("close");
            }
        });
    })

    function BuildCalendar(year) {
        var date = $.datepicker.parseDate("dd-mm-yy", "01-01-" + year);
        var d = date.getDate();
        var m = date.getMonth();
        var y = year == "" ? date.getFullYear() : year;

        var json = $.parseJSON(storedEvents);
        //        console.log(json);

        calendar = $('#calendar').fullCalendar({
            year: y,
            month: 0,
            date: 1,
            defaultView: 'month',
            header: {
                left: 'prev,next',
                center: 'title',
                //                right: 'month,agendaDay'
                right: 'month'
            },
            disableDragging: true,
            selectable: true,
            selectHelper: true,

            viewDisplay: function (view) {
                var now = $.datepicker.parseDate("dd-mm-yy", "01-01-" + year);
                var end = $.datepicker.parseDate("dd-mm-yy", "01-01-" + year);
                end.setMonth(now.getMonth() + 11); //Adjust as needed

                var cal_date_string = view.start.getMonth() + '/' + view.start.getFullYear();
                var cur_date_string = now.getMonth() + '/' + now.getFullYear();
                var end_date_string = end.getMonth() + '/' + end.getFullYear();

                if (cal_date_string == cur_date_string) { jQuery('.fc-button-prev').addClass("fc-state-disabled"); }
                else { jQuery('.fc-button-prev').removeClass("fc-state-disabled"); }

                if (end_date_string == cal_date_string) { jQuery('.fc-button-next').addClass("fc-state-disabled"); }
                else { jQuery('.fc-button-next').removeClass("fc-state-disabled"); }

            },

            //            dayClick: function (date, allDay, jsEvent, view) {
            //                //                var event = calendar.fullCalendar('clientEvents', $.fullCalendar.formatDate(date, "dd-MM-yyyy"));
            //                //                if (!event) {
            //                var title = prompt('Event Title:');
            //                if (title) {
            //                    calendar.fullCalendar('renderEvent',
            //            						{
            //            						    id: $.fullCalendar.formatDate(date, "dd-MM-yyyy"),
            //            						    title: title,
            //            						      start: $.fullCalendar.formatDate(date, "dd-MM-yyyy")
            //            						    //						    end: end,
            //            						    //						    allDay: allDay
            //            						},
            //            						true // make the event "stick"
            //            					);
            //                }
            //                //                }


            //                //                console.log(event);
            //            },
            select: function (start, end, allDay) {

                var id = $.fullCalendar.formatDate(start, "d-MM-yyyy");
                //                console.log(id);
                var event = calendar.fullCalendar('clientEvents', id);
                //                console.log(event);
                dateInYear.val(id);

                var title = "";
                try {
                    title = event[0].title;
                    //                    console.log(title);
                } catch (e) {

                }

                if ("@method" != "Detail") {
                    $("#txtNilaiHarian").val(title);
                    //                $("#divNilaiHarian").attr("visiblity", "visible");
                    $("#divNilaiHarian").removeAttr("style");
                    $("#divNilaiHarian").dialog({ modal: true });
                }
                //                var title = ""; // prompt('Event Title:');
                //                if (title) {
                //                    calendar.fullCalendar('renderEvent',
                //            						{
                //            						    id: start, // $.fullCalendar.formatDate(start, "dd-MM-yyyy"),
                //            						    title: title,
                //            						    start: start
                //            						},
                //            						true // make the event "stick"
                //            					);
                //                }
                //                calendar.fullCalendar('unselect');
            },
            editable: true,
            events: json
        })
    }


    //btnSimpanDanKeluar
    btnSimpanDanKeluar.click(function () {

        var date = $.datepicker.parseDate("dd-mm-yy", dateInYear.val());
        if (date.getFullYear() != year) {
            alert('tahun tidak berada pada tahun yang sama');
            return;
        }

        date = $.fullCalendar.formatDate(date, "d-MM-yyyy");
        //        console.log(date);
        var event = calendar.fullCalendar('clientEvents', date);
        //        console.log(event);

        //        var date = $.datepicker.parseDate("dd-mm-yy", dateInYear.val());
        //        var date = new Date(dateInYear.val());
        //        alert(date);
        //        alert($("#txtNilaiHarian").val());



        if (date && $("#txtNilaiHarian").val()) {
            if (!$.isNumeric($("#txtNilaiHarian").val())) {
                alert('harap masukkan angka');
                return;
            }

            if (event) {
                $('#calendar').fullCalendar('removeEvents', date);
            }
            //            alert('ok');
            var dateStart = $.datepicker.parseDate("dd-mm-yy", dateInYear.val());

            $("#calendar").fullCalendar('renderEvent',
                {
                    id: date, // $.fullCalendar.formatDate(start, "dd-MM-yyyy"),
                    title: $("#txtNilaiHarian").val(),
                    start: dateStart
                },
                true // make the event "stick"
            );
        }

        //        $("#calendar").fullCalendar('rerenderEvents')
        $("#divNilaiHarian").dialog('close');
        $("#divNilaiHarian").dialog("destroy");
        $("#divNilaiHarian").css("visibility", "hidden");

    });


</script>